#spring.application.name=customer-service
spring:
  application:
    name: customer
  profiles:
    active: dev
  config:
    import: configserver:http://127.0.0.1:8888

## for spring config server
  cloud:
    config:
      username: admin #or ${config_username} --high secured
      password: admin@123

management:
  endpoints:
    web:
      exposure:
        include: "*"